version: '3'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: qi-api-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: 1234 # root 用户mysql初始密码
      TZ: Asia/Shanghai
    ports:
      - "3306:3306" # 端口映射 todo修改
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./sql/docker.sql:/docker-entrypoint-initdb.d/init.sql # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork # 指定网络
  redis:
    image: redis:7
    container_name: qi-api-redis
    restart: always # 崩溃后自动重启
    ports:
      - "6379:6379"
    networks:
      - mynetwork
    volumes:
      - ./.redis-data:/data # 持久化
  nacos:
    image: nacos/nacos-server:v2.1.2
    hostname: nacos
    container_name: qi-api-nacos
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    restart: always # 崩溃后自动重启
    networks:
      - mynetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
networks:
  mynetwork:
