name: Bug Report
description: 使用简练详细的语言描述你遇到的问题.
title: "[Bug]: "
labels: ["bug"]
body:
- type: checkboxes
  id: Questioning
  attributes:
    label: 提问自检
    description: 请先检查有没有如下情况.
    options:
      - label: 我已确认目前没有类似 issue
      - label: 我已确认我已升级到最新版本
      - label: 我已完整查看过项目 README，尤其是常见问题部分
      - label: 我理解并愿意跟进此 issue，协助测试和提供反馈
      - label: 我理解并认可上述内容，并理解项目维护者精力有限，**不遵循规则**的 issue 可能会被无视或直接关闭



      
